lab10/Feeder/urls.py
from django.conf.urls import include,url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'',include('FeederApp.urls'))
]

lab10/FeederApp/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
	url(r'^$',views.login, name='login'),
	url(r'^register/',views.register,name='register'),
	url(r'^signup/',views.signup, name='signup'),
	url(r'^authadmin$',views.auth_admin,name='auth_admin'),
	url(r'^authinstruct$',views.auth_inst,name='auth_inst'),
	url(r'^admin_home$',views.admin_home,name='admin_home'),	
	url(r'^ins_home$',views.ins_home,name='ins_home'),
	url(r'^logout$',views.logout_view,name='logout'),
	url(r'^students$',views.student_list,name='student_list'),
	url(r'^instructors$',views.instructor_list,name='instructor_list'),
	url(r'^courses$',views.course_list,name='course_list'),
	url(r'^addcourse$',views.add_course,name='add_course'),
	url(r'^admin_profile$',views.admin_profile,name='admin_profile'),
	url(r'^update_admin$',views.update_admin,name='update_admin'),
	url(r'^createcourse$',views.make_course,name='make_course'),
	url(r'^addfeedback$',views.add_feedback,name='add_feedback'),
	url(r'^adddeadline$',views.add_deadline,name='add_deadline'),
	url(r'^viewdeadline$',views.view_deadline,name='view_deadline'),
	url(r'^viewfeedback$',views.view_feedback,name='view_feedback'),
	url(r'^createfeedback$',views.make_feedback,name='make_feedback'),
	url(r'^createdeadline$',views.make_deadline,name='make_deadline'),
	url(r'^instructor_profile$',views.instprofile,name='instprofile'),
	url(r'^addsttocourse/(?P<code>.*)$',views.add_stud_to_course,name='add_stud_to_course'),
	url(r'^ajax/modify/$',views.modify,name='modify'),
	url(r'^fb_login/$',views.fb_login,name='fb_login'),
	url(r'^viewresponses/(?P<feedbackid>\w{0,50})$',views.viewresponses,name='viewresponses'),	
	url(r'^viewobjective/(?P<feedbackid>\w{0,50})$',views.viewobjective,name='viewobjective'),	
	url(r'^updatedatabase$',views.updatedatabase,name='updatedatabase'),
	url(r'^stud_login',views.stud_login,name="stud_login"),
]

lab10/FeederApp/models.py
from __future__ import unicode_literals
from django.contrib.auth.models import User
from django.db import models
from datetime import date

class Student(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)	
	BRANCHES = (
        ('CS','Computer Science and Engineering'),
        ('EE', 'Electrical Engineering'),
        ('ME', 'Mechanical Engineering'),
        ('CL','Chemical Engineering'),
    )
	PROGRAM = (
		('BT','B.Tech.'),
		('MT','M.Tech.'),
		('DD','Dual Degree'),
	)
	roll_number = models.CharField(null = True,max_length=10)
	student_branch = models.CharField(null = True,max_length = 2,choices = BRANCHES)
	student_dob = models.DateField(null = True)
	student_program = models.CharField(null = True,max_length = 2,choices=PROGRAM)
	student_year  = models.IntegerField(null = True)

class Instructor(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)	
	BRANCHES = (
        ('CS','Computer Science and Engineering'),
        ('EE', 'Electrical Engineering'),
        ('ME', 'Mechanical Engineering'),
        ('CL','Chemical Engineering'),
    )
	instructor_branch = models.CharField(null = True,max_length = 2,choices = BRANCHES)
	instructor_dob = models.DateField(null = True)


class Course(models.Model):
	instructors = models.ManyToManyField(Instructor)
	students = models.ManyToManyField(Student)
	BRANCHES = (
        ('CS','Computer Science and Engineering'),
        ('EE', 'Electrical Engineering'),
        ('ME', 'Mechanical Engineering'),
        ('CL','Chemical Engineering'),
    )
	course_code = models.CharField(max_length=8,primary_key=True)
	course_name = models.CharField(max_length=100)
	course_branch = models.CharField(max_length = 2,choices = BRANCHES)
	course_credits = models.IntegerField()
	course_duration = models.DecimalField(max_digits = 2,decimal_places = 1)

class Deadlines(models.Model):
	NAME = (
		('ASS','Assignment'),
		('EX','Examination'),
		('FD','FeedBack'),
		)
	name = models.CharField(max_length=3,choices=NAME)
	desc = models.CharField(max_length = 100)
	date = models.DateField()
	code = models.CharField(max_length=10)
	course = models.ForeignKey(Course,on_delete=models.CASCADE,null =True)
	@property
	def is_past_due(self):
		if date.today() > self.date:
			return True
		return False


class Feedback(models.Model):
	deadline = models.OneToOneField(Deadlines,on_delete=models.CASCADE)
	course = models.ForeignKey(Course,on_delete=models.CASCADE)	
	name = models.CharField(max_length = 100)
	studentsresponded = models.TextField(null = True)
	id = models.AutoField(primary_key=True)

class Question(models.Model):
	TYPES = (
		('RB','Radio Buttons'),
		('TF','Text Field'),	
		)
	qid = models.AutoField(primary_key=True)
	question = models.CharField(max_length=100)
	question_type = models.CharField(max_length=2,choices = TYPES)
	response = models.TextField(null = True)
	feedback = models.ForeignKey(Feedback,on_delete=models.CASCADE,null = True)

lab10/FeederApp/views.py
from django.shortcuts import render,redirect    
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.contrib.auth.models import User
from django.contrib import messages
from FeederApp.models import *
from django.contrib.auth import authenticate
from django.contrib.auth import login as auth_login
from django.conf import settings
from django.shortcuts import redirect
from django.contrib.auth import logout
import urllib.request
import json
import csv
import io

def login(request):
	if request.user.is_authenticated:
		if request.user.username[0] == 'a':
			return redirect(admin_home)
		if request.user.username[0] == 'i':
			return redirect(ins_home)
		if request.user.username[0] == 's':
			return HttpResponse("Student is logged in")
			# We can also logout the person
		return HttpResponse("How??")
	return render(request,'login.html',{})    
def signup(request):
	return render(request,'signup.html',{})
def register(request):
	firstname = request.POST['firstname']
	lastname = request.POST['lastname']
	email = request.POST['email']
	dob = request.POST['birthdate']
	password = request.POST['password']
	branch = request.POST.get('branch')
	if email in list(map(lambda x:x['username'][2:],User.objects.all().values('username'))):
		messages.add_message(request, messages.ERROR, 'Username Already Exists.')
		return redirect('signup')
	else:
		newusr = User.objects.create_user("i:"+email,email,password) # Adding "i:" at the beginning of any instructer username
		newusr.first_name = firstname
		newusr.last_name = lastname
		newusr.save()
		newins = Instructor.objects.create(user = newusr,instructor_branch=branch,instructor_dob=dob)
		newins.save()
	messages.success(request, 'Congratulations!! Successful Signup!! Login to Continue')
	return redirect('login')

def auth_admin(request):
	adminname = request.POST['email']
	password = request.POST['password']
	user = authenticate(username="a:"+adminname, password=password)
	if user is not None:
		auth_login(request,user)
		return redirect('admin_home')
	else:
		messages.error(request, 'Bad Login Credentials')
		return redirect('login')

def auth_inst(request):
	email = request.POST['email']
	password = request.POST['password']
	user = authenticate(username="i:"+email,password=password)
	if user is not None:
		auth_login(request,user)
		return redirect('ins_home')
	else:
		messages.error(request, 'Bad Login Credentials')
		return redirect('login')

def fb_login(request):
	access_token = request.POST['access_token']
	url = 'https://graph.facebook.com/v2.8/me?fields=first_name,last_name,email&access_token='+access_token
	urlresponse = urllib.request.urlopen(url)
	response = json.loads(urlresponse.read().decode('utf-8'))
	firstname = response['first_name']
	lastname = response['last_name']
	email = response['email']
	username = 'i:'+email
	try:
		user = User.objects.get(username=username)
		auth_login(request,user)
		return redirect('ins_home')
	except Exception as e:
		newusr = User.objects.create_user(username,email) # Adding "i:" at the beginning of any instructer username
		newusr.first_name = firstname
		newusr.last_name = lastname
		newusr.save()
		newins = Instructor.objects.create(user = newusr)
		newins.save()
		auth_login(request,newusr)
		return redirect('ins_home')

def admin_home(request):
	if not request.user.is_authenticated:
		return redirect(login)
	try:
		user = User.objects.get(username=request.user.username)
		if not request.user.username[0] == "a":
			return HttpResponse('Page not Found')
		return render(request,'admin_home.html',{
			'admin':request.user
		})
	except Exception as e:
		return HttpResponse('Does not exist')

def ins_home(request):
	if not request.user.is_authenticated:
		return redirect(login)
	try:
		user = User.objects.get(username=request.user.username)
		if not request.user.username[0] == "i":
			return HttpResponse('Page not Found')
		return render(request,'instructor_home.html',{})
	except Exception as e:
		return HttpResponse('Page not Found')

def logout_view(request):
	if request.user.username[0] == "a":
		user = "a"
	else:
		user = "i"
	logout(request)
	return redirect('login')

def student_list(request):
	if request.user.username[0] == "a":
		return render(request,'student_list.html',{
			'students':Student.objects.all()
			})
	else:
		return HttpResponse("Don't try to be smart!! We ensure quite enough security!! :)")

def instructor_list(request):
	if request.user.username[0] == "a":
		return render(request,'instructor_list.html',{
			'instructors':Instructor.objects.all()
			})
	else:
		return HttpResponse("Don't try to be smart!! We ensure quite enough security!! :)")

def course_list(request):
	return render(request,'course_list.html',{
		'courses':Course.objects.all()
	})

def add_course(request):
	if request.user.username[0] == "a":
		return render(request,'add_course.html',{})
	else:
		return HttpResponse("Don't try to be smart!! We ensure quite enough security!! :)")
	
def admin_profile(request):
	if request.user.username[0] == "a":
		return render(request,'admin_profile.html',{})
	else:
		return HttpResponse("Don't try to be smart!! We ensure quite enough security!! :)")

def make_course(request):
	if request.user.username[0] == "a":
		cname = request.POST['cname']
		ccode = request.POST['ccode']
		duration = request.POST.get('duration')
		duration = int(duration)/2.0
		branch = request.POST.get('branch')
		credits = request.POST.get('credit')
		midsem = request.POST['midsem']
		endsem = request.POST['endsem']
		newcourse = Course.objects.create(course_name = cname,course_code=ccode,course_duration=duration,course_credits=credits,course_branch=branch)
		newcourse.save()
		mfdead = Deadlines.objects.create(course=newcourse,name='FD',desc='Mid-Semester Exam Feedback',date=midsem,code = ccode)
		mfdead.save()
		mfeed = Feedback.objects.create(course=newcourse,deadline=mfdead,name="Midsem Feedback")
		question1 = Question.objects.create(question="Do you have any comments or suggestions you would like to share about the instructor or the course?",question_type="TF")
		question1.save()
		mfeed.question_set.add(question1)
		question2 = Question.objects.create(question="Overall, the course was well organized.",question_type="RB")
		question2.save()
		mfeed.question_set.add(question2)
		question3 = Question.objects.create(question="The instructor was well prepared for each class.",question_type="RB")
		question3.save()
		mfeed.question_set.add(question3)
		question4 = Question.objects.create(question="Feedback on curriculum/course content",question_type="TF")
		question4.save()
		mfeed.question_set.add(question4)
		mfeed.save()

		efdead = Deadlines.objects.create(course=newcourse,name='FD',desc='End-Semester Exams Feedback',date=endsem,code = ccode)
		efdead.save()
		efeed = Feedback.objects.create(course=newcourse,deadline=efdead,name="Endsem Feedback")
		question1 = Question.objects.create(question="Do you have any comments or suggestions you would like to share about the instructor or the course?",question_type="TF")
		question1.save()
		efeed.question_set.add(question1)
		question2 = Question.objects.create(question="Overall, the course was well organized.",question_type="RB")
		question2.save()
		efeed.question_set.add(question2)
		question3 = Question.objects.create(question="The instructor was well prepared for each class.",question_type="RB")
		question3.save()
		efeed.question_set.add(question3)
		question4 = Question.objects.create(question="Feedback on curriculum/course content",question_type="TF")
		question4.save()
		efeed.question_set.add(question4)
		efeed.save()
		mdead = Deadlines.objects.create(course=newcourse,name='EX',desc='Mid-Semester Exams',date=midsem,code = ccode)
		mdead.save()
		edead = Deadlines.objects.create(course=newcourse,name='EX',desc='End-Semester Exams',date=endsem,code = ccode)
		edead.save()
		messages.add_message(request, messages.SUCCESS, 'Congratulations.New Course has been added!')
		messages.add_message(request,messages.INFO,'You can add new students to the course by clicking Add/Remove Students in Running Courses Menu')
		return redirect('admin_home')
	else:
		return HttpResponse("Don't try to be smart!! We ensure quite enough security!! :)")

def update_admin(request):
	if request.user.username[0] == "a":
		firstname = request.POST['firstname']
		lastname = request.POST['lastname']
		email = request.POST['email']
		password = request.POST['password']
		user = authenticate(username=request.user.username, password=password)
		if user is not None:
			user.first_name = firstname
			user.last_name = lastname
			user.email = email
			user.username = 'a:'+email
			user.save()
			messages.success(request, 'Profile Successfully Updated')
			return redirect('admin_home')
		else:
			messages.error(request, 'Wrong Password')
			return redirect('admin_home')
	else:
		return HttpResponse("Don't try to be smart!! We ensure quite enough security!! :)")

def add_feedback(request):
	if request.user.username[0] == "i":
		return render(request,'add_feedback.html',{
			'courses':Course.objects.all()
		})
	else:
		return HttpResponse("Don't try to be smart!! We ensure quite enough security!! :)")

def view_feedback(request):
	if request.user.username[0] == "i":
		return render(request,'view_feedback.html',{
			'courses':Course.objects.all()
		})
	else:
		return HttpResponse("Don't try to be smart!! We ensure quite enough security!! :)")

def add_deadline(request):
	if request.user.username[0] == "i":
		return render(request,'add_deadline.html',{
			'courses':Course.objects.all()
	})
	else:
		return HttpResponse("Don't try to be smart!! We ensure quite enough security!! :)")

def view_deadline(request):
	if request.user.username[0] == "i":
		return render(request,'view_deadline.html',{
			'courses':Course.objects.all()
	})
	else:
		return HttpResponse("Don't try to be smart!! We ensure quite enough security!! :)")

def instprofile(request):

lab10/FeederApp/templates/add_deadline.html
<div class="form anim-form">
<form action="createdeadline" onsubmit="return validateFeedbackForm()"  method="post">
	{% csrf_token %}
	<div class="form-group">
		<label>Select Course</label>
		<select class="form-control" name="dcourse">
		{% for course in courses %}
			<option value="{{course.course_code}}">{{course.course_code}} {{course.course_name}}</option>
		{% endfor %}
		</select>
	</div>
	<div class="form-group">
		<label for="type">Select The Type Of Deadline: </label>
		<label class="radio-inline"><input type="radio" name="type" value = "ASS" checked onclick="assignmentchecked()">Assignment</label>
		<label class="radio-inline"><input type="radio" name="type" value="EX" onclick="examclicked()">Examination</label>
	</div>
	<div class="form-group" id="textfieldforassignment">
		<input type="text" class="textinput" name = "deadlinedetails" required id="deadlinedetails" placeholder="Assignment Details">
	</div>
	<div class="form-group">
		<label class="control-label">Deadline</label>
		<input type="date" required id="deadlinedate" name="deadlinedate" class="form-control">
	</div>
	<button type="submit" class="btn btn-info col-sm-offset-4 col-sm-4">Add Deadline</button>
</form>
</div>

lab10/FeederApp/templates/add_feedback.html
<div class="form anim-form">
<form action="createfeedback" onsubmit="return validateFeedbackForm()"  method="post">
	{% csrf_token %}
	<div class="form-group">
		<label>Select Course</label>
		<select class="form-control" name="fcourse">
		{% for course in courses %}
			<option value="{{course.course_code}}">{{course.course_code}} {{course.course_name}}</option>
		{% endfor %}
		</select>
	</div>
	<div class="form-group">
		<input type="text" class="textinput" name = "fname" required id="description" placeholder="Feedback Name">
	</div>

	<div class="form-group">
	<label class="control-label">Deadline</label>
	<!-- <div class="col-sm-9"> -->
		<input type="date" required id="deadline" name="deadline" class="form-control">
	<!-- </div> -->
	</div>
	<br>
	<h3>Questions</h3>
	<br>
	<input type="hidden" id="qcount" name="qcount" value="0">
	<a href="#" onclick="addquestion('radio','Linear Scale Question','RB')" class="btn btn-info col-sm-5">Add Linear Scale</a> 
	<a href="#" onclick="addquestion('text','Text Question','TF')" class="btn btn-info col-sm-offset-2 col-sm-5">Add Subjective Question</a>
	<div id="questions">
	</div>
	<button type="submit" class="btn btn-info col-sm-offset-4 col-sm-4">Add Feedback</button>
</form>
</div>

lab10/FeederApp/templates/add_stud_to_course.html
<style>
input
{
	width:70px;
	height:30px;
	border-radius: 5px;
	background: #3F42F0;
	color:#ffffff;
	box-shadow: 2px 2px 2px #000000;
	border:0px;
    
}
</style>
<script>
$(document).ready(function()
{
	$("input").click(function()
	{
		ii = this.id
		$.ajax({
		type: 'POST',
        url: '/ajax/modify/',
        data: {
          csrfmiddlewaretoken: '{{ csrf_token }}',
          'id': this.id,
          'code': '{{ code }}'
        },
        success: function () {
        	// alert($("#"+ii).val())
        if($("#"+ii).val() == "Selected")
        	$("#"+ii).val("Select")
        else
        	$("#"+ii).val("Selected")
        }
      });
  		
	});
});
</script>
<table class="table table-condensed" style="border-bottom: 0.5px solid #ccc;">
	<thead>
	  <tr>
		<th>First Name</th>
		<th>Last Name</th>
		<th>Roll Number</th>
		<th>Branch</th>
		<th>Program</th>
		<th>Year</th>
		<th>Status</th>
	  </tr>
	</thead>
	<tbody>
	  {% for student in students %}
	  <tr style="max-height: 10px">
		<td>{{student.user.first_name}}</td>
		<td>{{student.user.last_name}}</td>
		<td>{{student.roll_number}}</td>
		<td>{{student.get_student_branch_display}}</td>
		<td>{{student.get_student_program_display}}</td>
		<td>{{student.student_year}}</td>
		<td>
			{% if course in student.course_set.all %}
			<input type="button" id = "{{student.user.id}}" value ="Selected" >
			{% else %}
			<input type="button" id = "{{student.user.id}}" value = "Select" >
			{% endif %}
		</td>
	  </tr>
	  {% endfor %}
			
	</tbody>
</table>

lab10/FeederApp/templates/admin_profile.html
<div class = "well" style="height: 300px;">
  	<form class="form-anim" method="post" action="update_admin">
		{% csrf_token %}
		<div class = "col-sm-6">
			<input required id="firstname" class="input-text" name="firstname" placeholder="First Name" value="{{ request.user.first_name }}">
		</div>
		<div class = "col-sm-6">
			<input required id="lastname" class="input-text" name="lastname" placeholder="Last Name" value="{{ request.user.last_name }}">
		</div>
		<div class="col-sm-12">
			<input type="email" name = "email" class = "input-text" required id="email" placeholder="Email" value="{{ request.user.email }}">
		</div>
		<div class="col-sm-12">
			<input type="password" name = "password" class = "input-text" required id="password" placeholder="Current Password">
		</div>
		<button type="submit" class="btn btn-info col-sm-offset-4 col-sm-4" style="background-color: #3F42F0; margin-top: 30px;"><span class="glyphicon glyphicon-save"></span>&nbsp;&nbsp;Update</button>
	</form>
</div>

lab10/FeederApp/templates/instructor_list.html
<table class="table table-condensed" style="border-bottom: 0.5px solid #ccc;">
	<thead>
		<tr>
			<th>First Name</th>
			<th>Last Name</th>
			<th>Email ID</th>
			<th>Branch</th>
		</tr>
	</thead>
	<tbody id="accordion">
		{% for instructor in instructors %}
		<tr class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" data-target="#acc{{ forloop.counter }}">
			<td>{{instructor.user.first_name}}</td>
			<td>{{instructor.user.last_name}}</td>
			<td>{{instructor.user.email}}</td>
			<td>{{instructor.get_instructor_branch_display}}</td>
		</tr>
		<!-- <tr>
			<td colspan="6" class="hidden-row">
				<div class="accordion-body collapse" id="acc{{ forloop.counter }}">
					<table class="table table-condensed">
						<thead>
							<tr>
								<th>#</th>
								<th>Courses Assigned To Instructor</th>
								<th>Course Credits</th>
							</tr>
						</thead>
						<tbody>
							{% for course in instructor.course_set.all %}
							<tr>
								<td>{{forloop.counter}}</td>
								<td>{{course.course_name}}</td>
								<td>{{course.course_credits}}</td>
							</tr>
							{% endfor %}
						</tbody>
					</table>
				</div>	  		
			</td>
		</tr> -->
		{% endfor %}
	</tbody>
</table>

lab10/FeederApp/templates/student_list.html
<table class="table table-condensed" style="border-bottom: 0.5px solid #ccc;">
	<thead>
		<tr>
		<th>First Name</th>
		<th>Last Name</th>
		<th>Roll Number</th>
		<th>Branch</th>
		<th>Program</th>
		<th>Year</th>
		</tr>
	</thead>
	<tbody id="accordion">
		{% for student in students %}
		<tr class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" data-target="#acc{{ forloop.counter }}">
			<td>{{student.user.first_name}}</a></td>
			<td>{{student.user.last_name}}</td>
			<td>{{student.roll_number}}</td>
			<td>{{student.get_student_branch_display}}</td>
			<td>{{student.get_student_program_display}}</td>
			<td>{{student.student_year}}</td>
		</tr>
		<tr>
		<td colspan="6" class="hidden-row">
		<div class="accordion-body collapse" id="acc{{ forloop.counter }}">
		<table class="table table-condensed">
			<thead>
				<tr>
					<th>#</th>
					<th>Courses Student Is Enrolled In</th>
					<th>Course Credits</th>
				</tr>
			</thead>
			<tbody>
				{% for course in student.course_set.all %}
				<tr>
					<td>{{forloop.counter}}</td>
					<td>{{course.course_name}}</td>
					<td>{{course.course_credits}}</td>
				</tr>
				{% endfor %}
			</tbody>
		</table>
		</div>
		</td>
		</tr>
		{% endfor %}
	</tbody>
</table>

lab10/FeederApp/templates/view_deadline.html
<p align="center">Click on a course to view its list of deadlines</p>
<table class="table" border="1px">

	<thead>
	  <tr>
		<th>Course Code</th>
		<th>Course Name</th>
		<th>Department</th>
		<th>Course Credits</th>
		<th>Duration</th>
	  </tr>
	</thead>
	<tbody id="accordion">
	<tr>
	</tr>
	  {% for course in courses %}
	<tr class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" data-target="#acc{{ forloop.counter }}" bgcolor="#DDDDDD">
		<td>{{course.course_code}}</td>
		<td>{{course.course_name}}</td>
		<td>{{course.course_branch}}</td>
		<td>{{course.course_credits}}</td>
		<td>{{course.course_duration}}</td>
	</tr>
	<tr class="hidden-row">
		<td colspan="6">
			<div class="accordion-body collapse" id="acc{{ forloop.counter }}">
				<p align="center"><b>In the past</b></p>
				<table class="table table-condensed" style="border-bottom: 0.5px solid #ccc;">
					<thead>
						<tr>
							<th>Deadline Type</th>
							<th>Deadline Description</th>
							<th>Deadline date</th>
						</tr>
					</thead>
					<tbody>
						{% for deadline in course.deadlines_set.all %}
						{% if deadline.is_past_due %}
							<tr bgcolor="#EEEEEE">
			  					<td>{{deadline.get_name_display}}</td>
			  					<td>{{deadline.desc}}</td>
			  					<td>{{deadline.date}}</td>
							</tr>
						{% endif %}
						{% endfor %}
					</tbody>
				</table>
				<p align="center"><b>In the future</b></p>
				<table class="table table-condensed" style="border-bottom: 0.5px solid #ccc;">
					<thead>
						<tr>
							<th>Deadline Type</th>
							<th>Deadline Description</th>
							<th>Deadline date</th>
						</tr>
					</thead>
					<tbody>						{% for deadline in course.deadlines_set.all %}
						{% if deadline.is_past_due %}
						{% else %}
							<tr bgcolor="#EEEEEE">
			  					<td>{{deadline.get_name_display}}</td>
			  					<td>{{deadline.desc}}</td>
			  					<td>{{deadline.date}}</td>
							</tr>
						{% endif %}
						{% endfor %}
					</tbody>
				</table>
			</div>	  		
		</td>
	</tr>
	  {% endfor %}
	</tbody>
  </table>

lab10/FeederApp/templates/view_feedback.html
<p align="center">Click on a course to view its list of feedbacks</p>
<table class="table">

	<thead>
	  <tr>
		<th>Course Code</th>
		<th>Course Name</th>
		<th>Department</th>
		<th>Course Credits</th>
		<th>Duration</th>
	  </tr>
	</thead>
	<tbody id="accordion">
	  {% for course in courses %}
	<tr class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" data-target="#acc{{ forloop.counter }}">
		<td>{{course.course_code}}</td>
		<td>{{course.course_name}}</td>
		<td>{{course.course_branch}}</td>
		<td>{{course.course_credits}}</td>
		<td>{{course.course_duration}}</td>
	</tr>
	<tr class="hidden-row">
		<td colspan="6">
			<div class="accordion-body collapse" id="acc{{ forloop.counter }}">
				<table class="table table-condensed" style="border-bottom: 0.5px solid #ccc;">
					<thead>
						<tr>
							<th>Deadline</th>
							<th>Feedback Name</th>
							<th>Student Responses</th>
							<th>Aggregate Results for Objective Questions</th>
						</tr>
					</thead>
					<tbody>
						{% for feedback in course.feedback_set.all %}
						<tr>
	  					<td>{{feedback.deadline.date}}</td>
	  					<td>{{feedback.name}}</td>
	  					<td><a href="/viewresponses/{{feedback.id}}" target="_blank">View</a></td>
	  					<td>View</td>
						</tr>
						{% endfor %}
					</tbody>
				</table>
			</div>	  		
		</td>
	</tr>
	  {% endfor %}
	</tbody>
  </table>