CS251project/django/FeederApp/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
	url(r'^$',views.login, name='login'),
	url(r'^register/',views.register,name='register'),
	url(r'^signup/',views.signup, name='signup'),
	url(r'^authadmin$',views.auth_admin,name='auth_admin'),
	url(r'^authinstruct$',views.auth_inst,name='auth_inst'),
	url(r'^admin_home$',views.admin_home,name='admin_home'),	
	url(r'^ins_home$',views.ins_home,name='ins_home'),
	url(r'^logout$',views.logout_view,name='logout'),
	url(r'^students$',views.student_list,name='student_list'),
	url(r'^instructors$',views.instructor_list,name='instructor_list'),
	url(r'^courses$',views.course_list,name='course_list'),
	url(r'^addcourse$',views.add_course,name='add_course'),
	url(r'^admin_profile$',views.admin_profile,name='admin_profile'),
	url(r'^update_admin$',views.update_admin,name='update_admin'),
	url(r'^update_ins$',views.update_ins,name='update_ins'),
	url(r'^createcourse$',views.make_course,name='make_course'),
	url(r'^addfeedback$',views.add_feedback,name='add_feedback'),
	url(r'^adddeadline$',views.add_deadline,name='add_deadline'),
	url(r'^viewdeadline$',views.view_deadline,name='view_deadline'),
	url(r'^viewfeedback$',views.view_feedback,name='view_feedback'),
	url(r'^feedbackresponse$',views.feedback_response,name='feedback_response'),
	url(r'^createfeedback$',views.make_feedback,name='make_feedback'),
	url(r'^createdeadline$',views.make_deadline,name='make_deadline'),
	url(r'^ins_profile$',views.instprofile,name='instprofile'),
	url(r'^addsttocourse/(?P<code>.*)$',views.add_stud_to_course,name='add_stud_to_course'),
	url(r'^ajax/modify/$',views.modify,name='modify'),
	url(r'^fb_login/$',views.fb_login,name='fb_login'),
	url(r'^viewresponses/(?P<feedbackid>\w{0,50})$',views.viewresponses,name='viewresponses'),	
	url(r'^viewobjective/(?P<feedbackid>\w{0,50})$',views.viewobjective,name='viewobjective'),	
	url(r'^updatedatabase$',views.updatedatabase,name='updatedatabase'),
	url(r'^stud_login',views.stud_login,name="stud_login"),
	url(r'^stud_home',views.stud_home,name="stud_home"),
	url(r'^graph/(?P<questionid>\w{0,50})$',views.matplotlibquestion,name="matplotlibquestion"),
]

CS251project/django/FeederApp/models.py
from __future__ import unicode_literals
from django.contrib.auth.models import User
from django.db import models
from datetime import date

class Student(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)	
	BRANCHES = (
        ('CS','Computer Science and Engineering'),
        ('EE', 'Electrical Engineering'),
        ('ME', 'Mechanical Engineering'),
        ('CL','Chemical Engineering'),
    )
	PROGRAM = (
		('BT','B.Tech.'),
		('MT','M.Tech.'),
		('DD','Dual Degree'),
	)
	roll_number = models.CharField(null = True,max_length=10)
	student_branch = models.CharField(null = True,max_length = 2,choices = BRANCHES)
	student_dob = models.DateField(null = True)
	student_program = models.CharField(null = True,max_length = 2,choices=PROGRAM)
	student_year  = models.IntegerField(null = True)

class Instructor(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)	
	BRANCHES = (
        ('CS','Computer Science and Engineering'),
        ('EE', 'Electrical Engineering'),
        ('ME', 'Mechanical Engineering'),
        ('CL','Chemical Engineering'),
    )
	instructor_branch = models.CharField(null = True,max_length = 2,choices = BRANCHES)

class Course(models.Model):
	instructors = models.ManyToManyField(Instructor)
	students = models.ManyToManyField(Student)
	BRANCHES = (
        ('CS','Computer Science and Engineering'),
        ('EE', 'Electrical Engineering'),
        ('ME', 'Mechanical Engineering'),
        ('CL','Chemical Engineering'),
    )
	course_code = models.CharField(max_length=8,primary_key=True)
	course_name = models.CharField(max_length=100)
	course_branch = models.CharField(max_length = 2,choices = BRANCHES)
	course_credits = models.IntegerField()
	course_semester = models.IntegerField()
	@property
	def is_fall_sem(self):
		if self.course_semester == 1:
			return True
		else:
			return False

class Deadlines(models.Model):
	NAME = (
		('ASS','Assignment'),
		('EX','Examination'),
		('FD','FeedBack'),
		)
	name = models.CharField(max_length=3,choices=NAME)
	desc = models.CharField(max_length = 100)
	date = models.DateField()
	code = models.CharField(max_length=10)
	course = models.ForeignKey(Course,on_delete=models.CASCADE,null =True)
	@property
	def is_past_due(self):
		if date.today() > self.date:
			return True
		return False


class Feedback(models.Model):
	deadline = models.OneToOneField(Deadlines,on_delete=models.CASCADE)
	course = models.ForeignKey(Course,on_delete=models.CASCADE)	
	name = models.CharField(max_length = 100)
	id = models.AutoField(primary_key=True)
	stud = models.ManyToManyField(Student)

class Question(models.Model):
	TYPES = (
		('RB','Radio Buttons'),
		('TF','Text Field'),
		('MCQ','Multiple Choice Question'),
		('DD','Drop Down List'),	
		)
	qid = models.AutoField(primary_key=True)
	question = models.CharField(max_length=100)
	question_type = models.CharField(max_length=2,choices = TYPES)
	response = models.TextField(null = True)
	options = models.TextField(null = True)
	feedback = models.ForeignKey(Feedback,on_delete=models.CASCADE,null = True)

CS251project/django/FeederApp/templates/add_course.html
<div class = "well" style="height: 500px; margin-top: 4%;">
	<form id="addcourse_form" class="form-anim" method="post" action="createcourse">
	{% csrf_token %}
		<div class="col-sm-12">
			<input type="text" class="input-text" name = "cname" required id="cname" placeholder="Course Name">
		</div>
		<div class="col-sm-12">
			<input type="text" class="input-text" name = "ccode" required id="ccode" placeholder="Course Code">
		</div>
		<div class="col-sm-3 label">
			Select Semester
		</div>
		<div class="col-sm-9 radio-group">
			<label class="radio-inline"><input type="radio" name="semester" value="1" checked>Fall</label>
			<label class="radio-inline"><input type="radio" name="semester" value="2">Spring</label>	
		</div>
		<div class="col-sm-3 label">
			Department
		</div>
		<div class="col-sm-9">
			<select name ="branch" class="input-text">
				<option selected disabled>Department</option>
				{% for branch in branches %}
				<option value="{{branch.0}}">{{branch.1}}</option>
				{% endfor %}
			</select>
		</div>
		<div class="col-sm-3 label">
			Select Credit
		</div>
		<div class = "col-sm-9">
			<select name="credit" class="input-text">
				<option value="3">3</option>
				<option value="4">4</option>
				<option value="6">6</option>
				<option value="8">8</option>
			</select>
		</div>
		<div class="col-sm-3 label">
			MidSem Date
		</div>
		<div class="col-sm-9">
			<input type="date" id="midsem" name="midsem" class="input-text" required="required">
		</div>
		<div class="col-sm-3 label">
			EndSem Date
		</div>
		<div class="col-sm-9">
			<input type="date" id="endsem" name="endsem" class="input-text" required="required">
		</div>
		<button type="submit" style="background-color:#3F42F0; margin-top: 30px;" class="btn btn-info col-sm-offset-4 col-sm-4">Add Course</button>
	</form>
</div>
<script type="text/javascript">
	$().ready(function() {
		$.validator.addMethod("regex", function(value,element,regexp){
			regexp = new RegExp(regexp);
			return this.optional(element) || regexp.test(value);
		},'Please enter a valid input!');

		$("#addcourse_form").validate({
		errorElement: 'div',
		rules: {
			cname: {
			required: true,
			maxlength: 100
			},
			ccode: {
			required: true,
			regex: /^[A-Z]{2}-[0-9]{3}$/
			},
			midsem: {
			required: true
			},
			endsem: {
			required: true
			},
			branch: {
			required: true
			},
		},
		messages: {
			cname: {
			required: "Please enter the Course Name",
			maxlength: "Course Name can't be more than 100 characters long"
			},
			ccode: {
			required: "Please enter Course Code",
			regex: "The Course Code entered is not valid"
			},
			email: {
			required: "Please enter your Email ID",
			email: "This is not a valid Email ID"
			},
			midsem: {
			required: "Please provide a Midsem Date"
			},
			endsem: {
			required: "Please provide an Endsem Date"
			},
			branch: {
			required: "Please select your department"
			},
		},

		submitHandler: function(form) {
			form.submit();
		}
		});
	});
</script>

CS251project/django/FeederApp/templates/add_deadline.html
<div class="well" style="height: 330px;margin-top:7%">
	<form class="form-anim" action="createdeadline" method="post">
		{% csrf_token %}
		<div class = "col-sm-3 label">Select Course</div>
		<div class = "col-sm-9">
		<select class="input-text" name="dcourse">
		{% for course in courses %}
			<option value="{{course.course_code}}">{{course.course_code}} {{course.course_name}}</option>
		{% endfor %}
		</select>
		</div>

		<div class="col-sm-5 label">
			Select The Type Of Deadline
		</div>
		<div class="col-sm-7 radio-group">
			<label class="radio-inline"><input type="radio" name="type" value = "ASS" checked onclick="assignmentchecked()">Assignment</label>
			<label class="radio-inline"><input type="radio" name="type" value="EX" onclick="examclicked()">Examination</label>
		</div>
		<div class="col-sm-12" id="textfieldforassignment">
			<input type="text" class="input-text" name = "deadlinedetails" required id="deadlinedetails" placeholder="Assignment Details">
		</div>
		<div class="label col-sm-3">Deadline</label></div>
		<div class="col-sm-9">
			<input type="date" required id="deadlinedate" name="deadlinedate" class="input-text">
		</div>
		<button type="submit" class="btn btn-info col-sm-offset-4 col-sm-4" style="background-color:#3F42F0; margin-top: 30px;">Add Deadline</button>
	</form>
</div>

CS251project/django/FeederApp/templates/add_feedback.html
<div class="well" style="height: 400px;margin-top:7%" id="feedback">
	<form class="form-anim" action="createfeedback" onsubmit="return validateFeedbackForm()"  method="post">
	{% csrf_token %}
	<div class = "col-sm-3 label">Select Course</div>
		<div class = "col-sm-9">
		<select class="input-text" name="fcourse">
		{% for course in courses %}
			<option value="{{course.course_code}}">{{course.course_code}} {{course.course_name}}</option>
		{% endfor %}
		</select>
		</div>
	<div class="col-sm-12">
		<input type="text" class="input-text" name = "fname" required id="description" placeholder="Feedback Name">
	</div>
	<div class="col-sm-5 label">
			Select The Deadline
	</div>
	<div class="col-sm-7">
		<input type="date" required id="deadline" name="deadline" class="input-text">
	</div>
	<div class="col-sm-12 label">
			Questions
	</div>
	<input type="hidden" id="qcount" name="qcount" value="0">
	<div class="col-sm-8">
	<select id="questiontoadd" required="required" class="input-text">
		<option value="RB">Linear List</option>
		<option value="TF">Add text response question</option>
		<option value="MCQ">Add multiple choice question</option>
		<option value="DD">Add drop down list</option>
	</select>
	</div>
	<button type="button" onclick="addquestion()" style="margin: 10px;margin-right:20px; height: 30px;float:right;" class="btn btn-info col-sm-3">Add</button>
	<div id="questions" class="row" style="color: #fff;">
	</div>
	<button type="submit" class="btn btn-info col-sm-offset-4 col-sm-4">Add Feedback</button>
</form>
</div>

CS251project/django/FeederApp/templates/rendercharts.html
<html>
<head>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	{% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
	<title>
		{{feedback.course.course_code}} :{{ feedback.name }}
	</title>
</head>
<body>
	<div class="container-fluid" align="center">
	<table margin="20px">
		<tr>
			<td><b>Feedback Name</b></td>
			<td>{{ feedback.name }}</td>
		</tr>
		<tr>
			<td><b>Course</b></td>
			<td>{{feedback.course.course_code}}, {{feedback.course.course_name}}</td>
		</tr>
	</table>
	</div>
	<div class="container-fluid" align="center">
	<table>
	<thead>
		<th>Question</th>
		<th>Plot</th>
	</thead>
	{% for question in feedback.question_set.all %}
		{% if question.question_type == 'RB' or question.question_type == 'MCQ' or question.question_type == 'CB' or question.question_type == 'DD' %}
		<tr>
		<td>{{question.question}}</td>
		<td><img src="/graph/{{question.qid}}" height="400px" width="400px" alt="No responses for the feedback form yet"></td>
		</tr>
		{% endif %}
	{% endfor %}
	</table>
	</div>
</body>
</html>

CS251project/django/FeederApp/templates/renderresponses.html
<html>
<head>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	{% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
	<title>
		{{feedback.course.course_code}} :{{ feedback.name }}
	</title>
</head>
<body>
	<div class="container-fluid" align="center">
	<table>
		<tr>
			<td><b>Feedback Name</b></td>
			<td>{{ feedback.name }}</td>
		</tr>
		<tr>
			<td><b>Course</b></td>
			<td>{{feedback.course.course_code}}, {{feedback.course.course_name}}</td>
		</tr>
	</table>
	</div>
	<div class="container" >
	{% if responses %}
		<div class="container-fluid" align="center">
		<table>
		{% for response in responses %}
			<tr>
			<td>
			<h3> Response {{ forloop.counter }} </h3>
			</td>
			<td>
			<div class="container-fluid" align="center">
			<table>
			<thead>
				<th>Question</th>
				<th>Response</th>
			</thead>
			{% for answer in response %}
				<tr>
				{% for info in answer %}
				<td> {{ info }} </td>
				{% endfor %}
				</tr>
			{% endfor %}
			</table>
			</div>
			</td>
			</tr>
		{% endfor %}
		</table>
		</div>
	{% else %}
		<h1 align="center"> No responses yet</h1>
	{% endif %}
	</div>
</body>
</html>